#!/usr/bin/env python3
"""Regenerate the six story covers and inject them into the story pages.

    python3 tools/scenes/build_covers.py            # all six
    python3 tools/scenes/build_covers.py 03 05      # just these

Each cover is composed in covers.py from scenelib backgrounds plus the real
character figures generated by tools/portraits. The <svg> inside
`<div class="cover-illustration">` is generated output: edit covers.py, not the
story HTML, or the next build will overwrite your changes.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))

import covers  # noqa: E402

COVER_RE = re.compile(r'(<div class="cover-illustration">\s*)(<svg\b.*?</svg>)(\s*</div>)', re.S)


def main(argv):
    wanted = argv[1:]
    total = 0
    for slug, build in covers.COVERS.items():
        if wanted and not any(slug.startswith(w) for w in wanted):
            continue
        page = os.path.join(ROOT, 'stories', slug, 'index.html')
        if not os.path.exists(page):
            raise SystemExit(f'no such story page: {page}')
        svg = build()
        html = open(page).read()
        if not COVER_RE.search(html):
            raise SystemExit(f'{slug}: could not find the cover <svg> inside .cover-illustration')
        html = COVER_RE.sub(lambda m: m.group(1) + svg + m.group(3), html, count=1)
        open(page, 'w').write(html)
        total += len(svg)
        print(f'  {slug}: {len(svg)/1024:.0f} KB')
    print(f'injected {total/1024:.0f} KB of cover SVG')


if __name__ == '__main__':
    main(sys.argv)
